### ISSUE TITLE
Bug: Perforce Helix Core fails without HAS

### ISSUE THREAD

**Issue by henrykie** [aws-games/cloud-game-development-toolkit#218]
### Expected Behaviour

When no `helix_authentication_service_url` is specified in the Helix Core module the HAS extension should not be configured.

### Current Behaviour

When no `helix_authentication_service_url` is specified the HAS extension attempts to configure against a null URL and fails thus preventing Helix Core startup.

### Possible Solution

Adjust the `p4_configure.sh` script and the `user_data` in the Helix Core module to support null HAS URL variables.

### Steps to Reproduce

Provision a helix core server module without specifying `helix_authentication_service_url`

### Cloud Game Development Toolkit version

latest

**Comment by henrykie** [comment]
@GrzesiekO want to take a stab at this?

**Comment by GrzesiekO** [comment]
Sure

**Comment by henrykie** [comment]
/var/log/p4_configure includes the HAS extension configuration logging, and that is where I was able to detect the failure. Maybe we need to pass arguments to p4_configure shell script with flags to handle null values?

**Comment by GrzesiekO** [comment]
> /var/log/p4_configure includes the HAS extension configuration logging, and that is where I was able to detect the failure. Maybe we need to pass arguments to p4_configure shell script with flags to handle null values?

I have a fix with extended configuration for the p4_configure so instead of providing raw values in parameters it will that flags:
--nfs hxmetadata=<>, hxlogs=<>, hxdepots=<>
--ebs hxmetadata=<>, hxlogs=<>, hxdepots=<>
--auth user=<>, passwd=<>
--has hasurl=<>

**Comment by henrykie** [comment]
we still p4d type (master or replica)

**Comment by GrzesiekO** [comment]
Fixed in PR #239 all features added:
Arm64 support
Long parameters for p4_configure:
"Options:"
 --p4d_type <type>        Specify the type of Helix Core server (p4d_commit, p4d_replica, p4d_edge)"
 --username <secret_id>   AWS Secrets Manager secret ARN for the Helix Core admin username"
 --password <secret_id>   AWS Secrets Manager secret ARN for the Helix Core admin password"
 --auth <url>             Helix Authentication Service URL"
 --fqdn <hostname>        Fully Qualified Domain Name for the Helix Core server"
 --hx_logs <path>         Path for Helix Core logs device or share"
 --hx_metadata <path>     Path for Helix Core metadata device or share"
 --hx_depots <path>       Path for Helix Core depots device or share"

**Comment by GrzesiekO** [comment]
Fixed as per above and PR #239
