### ISSUE TITLE
Feature request: Ability to set case sensitivity in Helix Core

### ISSUE THREAD

**Issue by keith-miller** [aws-games/cloud-game-development-toolkit#302]
### Use case

Helix Core `p4d` has a list of startup flags that can be passed in to achieve different things (a full list can be found [here](https://www.perforce.com/manuals/p4sag/Content/P4SAG/appendix.p4d.html) ). 

For example, both Windows and UGS require the server to be run in case insensitive mode, which is the `-C1` startup flag.  

### Solution/User Experience

Add some ability to set the case sensitivity in the `helix-core` module on setup.

**Comment by henrykie** [comment]
@GrzesiekO We need to make updates to `p4_configure` script

**Comment by henrykie** [comment]
The `p4_configure.sh` script leverages [`mkdirs.cfg`](https://swarm.workshop.perforce.com/files/guest/perforce_software/sdp/dev/Server/Unix/setup/mkdirs.cfg) for configuration of the Perforce Helix Core server on deployment. This config file provides the following:

```
# CASE_SENSITIVE settings:
# 0 -- Server will run '-C1' mode, forcing case-insensitive mode on normally case-sensitive platforms
#      such as Linux
# 1 -- Server will run with case sensitivity default of the underlying platform (Unix is case sensitive).
 
CASE_SENSITIVE=1
```

We need to provide an additional flag to the `p4_configure.sh` script that can be called on instance provisioning. Perhaps something like `--case-sensitive 0` or `--case-sensitive 1`. We could also use a boolean flag that would just check for inclusion of `--case-insensitive` flag, but this might get semantically confusing since the actual variable being updated in `mkdirs.cfg` is `CASE_SENSITIVE`.

Regardless, any change to this script will require an AMI rebuild and a subsequent redeploy of a Perforce Helix Core server.

**Comment by GrzesiekO** [comment]
> The `p4_configure.sh` script leverages [`mkdirs.cfg`](https://swarm.workshop.perforce.com/files/guest/perforce_software/sdp/dev/Server/Unix/setup/mkdirs.cfg) for configuration of the Perforce Helix Core server on deployment. This config file provides the following:
> 
> ```
> # CASE_SENSITIVE settings:
> # 0 -- Server will run '-C1' mode, forcing case-insensitive mode on normally case-sensitive platforms
> #      such as Linux
> # 1 -- Server will run with case sensitivity default of the underlying platform (Unix is case sensitive).
>  
> CASE_SENSITIVE=1
> ```
> 
> We need to provide an additional flag to the `p4_configure.sh` script that can be called on instance provisioning. Perhaps something like `--case-sensitive 0` or `--case-sensitive 1`. We could also use a boolean flag that would just check for inclusion of `--case-insensitive` flag, but this might get semantically confusing since the actual variable being updated in `mkdirs.cfg` is `CASE_SENSITIVE`.
> 
> Regardless, any change to this script will require an AMI rebuild and a subsequent redeploy of a Perforce Helix Core server.

For any new deployments setting up case insensitive for case sensitive system like Linux is straightforward as mentioned by @henrykie. Changes to a deployed server with data in it, would require additional steps that are not covered by CGD toolkit.

**Comment by keith-miller** [comment]
That solution works for us and our use case

**Comment by keith-miller** [comment]
I have updated the ticket to reflect that this is just for case sensitivity support.
